char    ps_header[] = "%%!PS-Adobe-3.0\n"
"%%%%BoundingBox: 24 24 588 768\n"
"%%%%Title: ObjectManager Output\n"
"%%%%For: you\n"
"%%%%Creator: Advantio ObjectManager\n"
"%%%%CreationDate: today\n"
"%%%%Orientation: Portrait\n"
"%%%%Pages: (atend)\n"
"%%%%DocumentMedia: Letter 800 792 0 () ()\n"
"%%%%DocumentNeededResources: (atend)\n"
"%%%%EndComments\n"
"%%%%BeginProlog\n"
"%%%%BeginResource: procset Enscript-Prolog 1.6 1\n"
"%%\n"
"%% Procedures.\n"
"%%\n"
"/_S {\n"
"  /_s save def\n"
"} def\n"
"/_R {\n"
"  _s restore\n"
"} def\n"
"/S {\n"
"  gsave\n"
"  showpage\n"
"  grestore\n"
"} bind def\n"
"/MF {\n"
"  /newfontname exch def\n"
"  /fontname exch def\n"
"  /fontdict fontname findfont def\n"
"  /newfont fontdict maxlength dict def\n"
"  fontdict {\n"
"    exch\n"
"    dup /FID eq {\n"
"      pop pop\n"
"    } {\n"
"      exch newfont 3 1 roll put\n"
"    } ifelse\n"
"  } forall\n"
"  newfont /FontName newfontname put\n"
"  encoding_vector length 256 eq {\n"
"    newfont /Encoding encoding_vector put\n"
"  } if\n"
"  newfontname newfont definefont pop\n"
"} def\n"
"/SF { \n"
"  /height exch def\n"
"  /width exch def\n"
"  findfont\n"
"  [width 0 0 height 0 0] makefont setfont\n"
"} def\n"
"/SUF {\n"
"  /height exch def\n"
"  /width exch def\n"
"  /F-gs-user-font MF\n"
"  /F-gs-user-font width height SF\n"
"} def\n"
"/M {moveto} bind def\n"
"/s {show} bind def\n"
"/Box {\n"
"  /d_h exch def /d_w exch def /d_y exch def /d_x exch def\n"
"  d_x d_y  moveto\n"
"  d_w 0 rlineto\n"
"  0 d_h rlineto\n"
"  d_w neg 0 rlineto\n"
"  closepath\n"
"} def\n"
"/bgs {\n"
"  /str exch def\n"
"  /gray exch def\n"
"  /blskip exch def\n"
"  /height exch def\n"
"  /y exch def\n"
"  /x exch def\n"
"  gsave\n"
"    x y blskip sub str stringwidth pop height Box\n"
"    gray setgray\n"
"    fill\n"
"  grestore\n"
"  x y M str s\n"
"} def\n"
"/highlight_bars {\n"
"  gsave\n"
"    setgray\n"
"    /ymarg exch def\n"
"    /lineheight exch def\n"
"    /nlines exch def\n"
"    0 d_header_y ymarg sub 2 sub translate\n"
"    /cw d_output_w cols div def\n"
"    /nrows d_output_h ymarg 2 mul sub lineheight div cvi def\n"
"    0 1 cols 1 sub {\n"
"      cw mul /xp exch def\n"
"      0 1 nrows 1 sub {\n"
"        /rn exch def\n"
"        rn lineheight mul neg /yp exch def\n"
"        rn nlines idiv 2 mod 0 eq {\n"
"	  xp 4 add yp cw 8 sub lineheight neg Box fill\n"
"	} if\n"
"      } for\n"
"    } for\n"
"  grestore\n"
"} def\n"
"/line_highlight {\n"
"  gsave\n"
"    /gray exch def\n"
"    Box gray setgray fill\n"
"  grestore\n"
"} def\n"
"/column_lines {\n"
"  gsave\n"
"    .1 setlinewidth\n"
"    0 d_footer_h translate\n"
"    /cw d_output_w cols div def\n"
"    1 1 cols 1 sub {\n"
"      cw mul 0 moveto\n"
"      0 d_output_h rlineto stroke\n"
"    } for\n"
"  grestore\n"
"} def\n"
"/column_borders {\n"
"  gsave\n"
"    .1 setlinewidth\n"
"    0 d_footer_h moveto\n"
"    0 d_output_h rlineto\n"
"    d_output_w 0 rlineto\n"
"    0 d_output_h neg rlineto\n"
"    closepath stroke\n"
"  grestore\n"
"} def\n"
"/draw_underlay {\n"
"  ul_style 0 eq {\n"
"    ul_str true charpath stroke\n"
"  } {\n"
"    ul_str show\n"
"  } ifelse\n"
"} def\n"
"/underlay {\n"
"  gsave\n"
"    0 d_page_h translate\n"
"    d_page_h neg d_page_w atan rotate\n"
"    ul_gray setgray\n"
"    ul_font setfont\n"
"    /dw d_page_h dup mul d_page_w dup mul add sqrt def\n"
"    ul_str stringwidth pop dw exch sub 2 div ul_h_ptsize -2 div moveto\n"
"    draw_underlay\n"
"  grestore\n"
"} def\n"
"/user_underlay {\n"
"  gsave\n"
"    ul_x ul_y translate\n"
"    ul_angle rotate\n"
"    ul_gray setgray\n"
"    ul_font setfont\n"
"    0 0 ul_h_ptsize 2 div sub moveto\n"
"    draw_underlay\n"
"  grestore\n"
"} def\n"
"/page_prefeed {	\n"
"  statusdict /prefeed known {\n"
"    statusdict exch /prefeed exch put\n"
"  } {\n"
"    pop\n"
"  } ifelse\n"
"} def\n"
"/wrapped_line_mark {\n"
"  /type exch def\n"
"  /h exch def\n"
"  /w exch def\n"
"  /y exch def\n"
"  /x exch def\n"
"  type 2 eq {\n"
"    gsave\n"
"      0 setlinewidth\n"
"      x w 4 div add y M\n"
"      0 h rlineto w 2 div 0 rlineto 0 h neg rlineto\n"
"      closepath fill\n"
"    grestore\n"
"  } {\n"
"    type 3 eq {\n"
"      gsave\n"
"        .2 setlinewidth\n"
"        x w 2 div add y h 2 div add M\n"
"        w 4 div 0 rlineto\n"
"        x w 4 div add y lineto stroke\n"
"        x w 4 div add w 8 div add y h 4 div add M\n"
"        x w 4 div add y lineto\n"
"	w 4 div h 8 div rlineto stroke\n"
"      grestore\n"
"    } {\n"
"    } ifelse\n"
"  } ifelse\n"
"} def\n"
"/BeginEPSF {\n"
"  /b4_Inc_state save def  \n"
"  /dict_count countdictstack def\n"
"  /op_count count 1 sub def\n"
"  userdict begin\n"
"  /showpage { } def\n"
"  0 setgray 0 setlinecap\n"
"  1 setlinewidth 0 setlinejoin\n"
"  10 setmiterlimit [ ] 0 setdash newpath\n"
"  /languagelevel where {\n"
"    pop languagelevel\n"
"    1 ne {\n"
"      false setstrokeadjust false setoverprint\n"
"    } if\n"
"  } if\n"
"} bind def\n"
"/EndEPSF {\n"
"  count op_count sub { pos } repeat\n"
"  countdictstack dict_count sub { end } repeat\n"
"  b4_Inc_state restore\n"
"} bind def\n"
"/languagelevel where {\n"
"  pop /gs_languagelevel languagelevel def\n"
"} {\n"
"  /gs_languagelevel 1 def\n"
"} ifelse\n"
"/encoding_vector [\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/space        	/exclam       	/quotedbl     	/numbersign   	\n"
"/dollar       	/percent      	/ampersand    	/quoteright   	\n"
"/parenleft    	/parenright   	/asterisk     	/plus         	\n"
"/comma        	/hyphen       	/period       	/slash        	\n"
"/zero         	/one          	/two          	/three        	\n"
"/four         	/five         	/six          	/seven        	\n"
"/eight        	/nine         	/colon        	/semicolon    	\n"
"/less         	/equal        	/greater      	/question     	\n"
"/at           	/A            	/B            	/C            	\n"
"/D            	/E            	/F            	/G            	\n"
"/H            	/I            	/J            	/K            	\n"
"/L            	/M            	/N            	/O            	\n"
"/P            	/Q            	/R            	/S            	\n"
"/T            	/U            	/V            	/W            	\n"
"/X            	/Y            	/Z            	/bracketleft  	\n"
"/backslash    	/bracketright 	/asciicircum  	/underscore   	\n"
"/quoteleft    	/a            	/b            	/c            	\n"
"/d            	/e            	/f            	/g            	\n"
"/h            	/i            	/j            	/k            	\n"
"/l            	/m            	/n            	/o            	\n"
"/p            	/q            	/r            	/s            	\n"
"/t            	/u            	/v            	/w            	\n"
"/x            	/y            	/z            	/braceleft    	\n"
"/bar          	/braceright   	/tilde        	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/.notdef      	/.notdef      	/.notdef      	/.notdef      	\n"
"/space        	/exclamdown   	/cent         	/sterling     	\n"
"/currency     	/yen          	/brokenbar    	/section      	\n"
"/dieresis     	/copyright    	/ordfeminine  	/guillemotleft	\n"
"/logicalnot   	/hyphen       	/registered   	/macron       	\n"
"/degree       	/plusminus    	/twosuperior  	/threesuperior	\n"
"/acute        	/mu           	/paragraph    	/bullet       	\n"
"/cedilla      	/onesuperior  	/ordmasculine 	/guillemotright	\n"
"/onequarter   	/onehalf      	/threequarters	/questiondown 	\n"
"/Agrave       	/Aacute       	/Acircumflex  	/Atilde       	\n"
"/Adieresis    	/Aring        	/AE           	/Ccedilla     	\n"
"/Egrave       	/Eacute       	/Ecircumflex  	/Edieresis    	\n"
"/Igrave       	/Iacute       	/Icircumflex  	/Idieresis    	\n"
"/Eth          	/Ntilde       	/Ograve       	/Oacute       	\n"
"/Ocircumflex  	/Otilde       	/Odieresis    	/multiply     	\n"
"/Oslash       	/Ugrave       	/Uacute       	/Ucircumflex  	\n"
"/Udieresis    	/Yacute       	/Thorn        	/germandbls   	\n"
"/agrave       	/aacute       	/acircumflex  	/atilde       	\n"
"/adieresis    	/aring        	/ae           	/ccedilla     	\n"
"/egrave       	/eacute       	/ecircumflex  	/edieresis    	\n"
"/igrave       	/iacute       	/icircumflex  	/idieresis    	\n"
"/eth          	/ntilde       	/ograve       	/oacute       	\n"
"/ocircumflex  	/otilde       	/odieresis    	/divide       	\n"
"/oslash       	/ugrave       	/uacute       	/ucircumflex  	\n"
"/udieresis    	/yacute       	/thorn        	/ydieresis    	\n"
"] def\n"
"/HFpt_w 10 def\n"
"/HFpt_h 10 def\n"
"/Courier-Bold /HF-gs-font MF\n"
"/HF /HF-gs-font findfont [HFpt_w 0 0 HFpt_h 0 0] makefont def\n"
"/Courier /F-gs-font MF\n"
"/F-gs-font 10 10 SF\n"
"/#copies 1 def\n"
"gs_languagelevel 1 gt {\n"
"  <<\n"
"    /PageSize [800 792] \n"
"  >> setpagedevice\n"
"} if\n"
"/do_header {\n"
"  gsave\n"
"    d_header_x d_header_y HFpt_h 3 div add translate\n"
"    HF setfont\n"
"    user_header_p {\n"
"      5 0 moveto user_header_left_str show\n"
"      d_header_w user_header_center_str stringwidth pop sub 2 div\n"
"      0 moveto user_header_center_str show\n"
"      d_header_w user_header_right_str stringwidth pop sub 5 sub\n"
"      0 moveto user_header_right_str show\n"
"    } {\n"
"      5 0 moveto fname show\n"
"      45 0 rmoveto fmodstr show\n"
"      45 0 rmoveto pagenumstr show\n"
"    } ifelse\n"
"  grestore\n"
"} def\n"
"/d_page_w 564 def\n"
"/d_page_h 744 def\n"
"/d_header_x 0 def\n"
"/d_header_y 729 def\n"
"/d_header_w 564 def\n"
"/d_header_h 15 def\n"
"/d_footer_x 0 def\n"
"/d_footer_y 0 def\n"
"/d_footer_w 564 def\n"
"/d_footer_h 0 def\n"
"/d_output_w 564 def\n"
"/d_output_h 729 def\n"
"/cols 1 def\n"
"%%Page: (1) 1\n"
"%%BeginPageSetup\n"
"_S\n"
"24 24 translate\n"
"/pagenum 1 def\n"
"/fname (Advantio) def\n"
"/fdir () def\n"
"/ftail (Advantio) def\n"
"/fmodstr (Sat May 20 00:03:44 2000) def\n"
"/pagenumstr (1) def\n"
"/user_header_p false def\n"
"do_header\n";

/*
"5 716 M\n"
"(a1      a2      a3) s\n"
"5 705 M\n"
"(b1      b2      b3) s\n"
"5 694 M\n"
"(c1      c2      c3) s\n"
*/

char    ps_footer[] = "_R\n"
"S\n";

char    ps_newpage[] = "%%%%Page: (%d) %d\n"
"%%%%BeginPageSetup\n"
"_S\n"
"24 24 translate\n"
"/pagenum %d def\n"
"/fname (Advantio) def\n"
"/fdir () def\n"
"/ftail (Advantio) def\n"
"/fmodstr (Advantio) def\n"
"/pagenumstr (%d) def\n"
"/user_header_p false def\n"
"do_header\n";

